# Exploring Numpy's Ufuncs

In [1]:
import numpy as np
# Array Arithmetic
x = np.arange(4)
print(x)
print(x+5) #addition
print(x-5) #subtraction
print(x*2) #multiplication
print(x/2) #division
print(x//2) #floor division

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]


In [2]:
# Absolute value
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

# Trigonometric functions

In [3]:
# Defining an array of angles
theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# Inverse Trigonometric functions

In [4]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


# Exponents and Logarithms

In [5]:
x = [1,2,3]
print(x)
print(np.exp(x))
print(np.exp2(x))
print(np.power(3,x))

[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]


In [6]:
# Summing the values in an array
L = np.random.random(100)
np.sum(L)

49.91383360770898

In [7]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

2.45 s ± 1.1 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
5.55 ms ± 957 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
np.min(big_array)

7.888394395472176e-07

In [9]:
np.max(big_array)

0.9999975138779851