# Numpy Array Attributes

In [1]:
import numpy as np

np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=(3,4,5))

# Print dimensions, shape and size of the array

In [2]:
print("x1 ndim: ", x1.ndim)  #printing number of dimensions of array
print("x1 shape: ", x1.shape)  #printing the size of each dimension
print("x1 size: ", x1.size)  #printing total size of array
print("dtype: ", x1.dtype)  # printing the data type of array
print("itemsize: ", x1.itemsize) #printing size of each array element
print("nbytes: ", x1.nbytes)  #printing the total size of array

x1 ndim:  3
x1 shape:  (3, 4, 5)
x1 size:  60
dtype:  int32
itemsize:  4
nbytes:  240


# Array Indexing: Accessing Single Elements

In [3]:
x2=np.array([5, 0, 3, 3, 7, 9])

In [4]:
x2[0] # print first element

5

In [5]:
x2[-1] #print last element

9

# Multidimensional Arrays

In [6]:
x3=np.array([[3, 5, 2, 4],
            [7, 6, 8, 8],
            [1, 6, 7, 7]])

In [7]:
x3[0,0] #print first element

3

In [8]:
x3[2, -1] #print last element of 2nd row

7

# Modify values of Array

In [9]:
x3[0, 0] = 12
x3

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Array Slicing: Accessing Subarrays

# One dimensional Subarrays

In [10]:
x = np.arange(10)

In [11]:
x[:5] # first 5 elements

array([0, 1, 2, 3, 4])

In [12]:
x[5:] #elements after index 5

array([5, 6, 7, 8, 9])

In [13]:
x[::2] #every alternate element

array([0, 2, 4, 6, 8])

In [14]:
x[::-1] # reversed array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Multidimensional Subarrays

In [15]:
x3=np.array([[3, 5, 2, 4],
            [7, 6, 8, 8],
            [1, 6, 7, 7]])

In [16]:
x3[:2, :3] #two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [17]:
x3[:3, ::2] #all rows, every alternate column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [18]:
x3[::-1, ::-1] # subarray dimensions reversed together

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [19]:
x3[:, 0] #first column of x3

array([3, 7, 1])

In [20]:
x3[0, :] # first row of x2

array([3, 5, 2, 4])

# Reshaping of Arrays

In [21]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array concatenation 

In [22]:
x=np.array([1, 2, 3])
y=np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

# Working with arrays of mixed dimensions

In [23]:
x=np.array([1, 2, 3])
grid=np.array([[9, 8, 7],
              [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [24]:
grid=np.array([[9, 8, 7],
              [6, 5, 4]])
y=np.array([[99],
           [99]])

np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Splitting of Arrays

In [25]:
x=[1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]
