# Import Numpy library

In [1]:
import numpy as np

# Creating Numpy Arrays from Python Lists

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

# Creating Multidimensional Numpy Array

In [5]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating Arrays from Scratch

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Create a 3*5 array filled with 3.14

In [8]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

# Create an array filled with linear sequence starting at 0 and ending at 20.

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Create an array of five values evenly spaced between 0 and 1

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Create a 3*3 array of uniformly distributed random values between 0 and 1

In [11]:
np.random.random((3, 3))

array([[0.24661656, 0.80883766, 0.56024123],
       [0.91099108, 0.05515245, 0.90802034],
       [0.61220668, 0.50195609, 0.9554839 ]])

# Create a 3*3 normally distributed random values with mean 0 and standard deviation 1

In [12]:
np.random.normal(0, 1, (3, 3))

array([[ 1.17340619, -0.15651154,  0.76316663],
       [-0.61790253,  0.92710314, -0.62905411],
       [ 0.28271581,  2.44395813,  0.90964729]])

# Create a 3* 3 array of random integers in the interval [0, 10)

In [13]:
np.random.randint(0, 10, (3, 3))

array([[2, 0, 8],
       [8, 4, 2],
       [2, 8, 9]])

# Create a 3*3 identity matrix

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])